### ISSUE TITLE
strange results in memory, disk usage, and gpu

### ISSUE THREAD

**Issue by generaltso** [woodruffw/screenfetch-c#17]
![2015-04-20-152148_1024x768_scrot](https://cloud.githubusercontent.com/assets/8731605/7238587/5f6837ee-e771-11e4-8726-1c4bdbb04ef5.png)
![2015-04-20-152212_1024x768_scrot](https://cloud.githubusercontent.com/assets/8731605/7238588/5f68f940-e771-11e4-9d2d-8f165eceb686.png)

KittyKatt's screenFetch for comparison; It's a ThinkPad T60 with stock everything.

**Comment by woodruffw** [comment]
Those GPU results are expected - the '945M' is an integrated GPU made by Intel.

The disk reporting problems should be fixed by b5832148d9b303ee048b34be2b910e030ced7a37.

The memory reporting problems are more difficult - Linux only seems to expose cache use in `/proc/meminfo`. I'm doing more research on fixing this.

**Comment by generaltso** [comment]
Still bork
![2015-04-24-194943_1024x768_scrot](https://cloud.githubusercontent.com/assets/8731605/7330359/4075ea96-eabb-11e4-9c27-d3517a21d5a3.png)
